server:
  port: 8101

spring:
  profiles: 
    active:
      - dev
--- 
spring:
  profiles: dev #开发环境
  application:
    name: springcloud-user-provider-dev
--- 
spring:
  profiles: test #测试环境
  application:
    name: springcloud-user-provider-test
--- 
spring:
  profiles: prod #生产环境
  application:
    name: springcloud-user-provider-prod
